### ISSUE TITLE
MySql Connection doesen't work 

### ISSUE THREAD

**Issue by FLO-server** [Hyfe-JavaDebug/battle-pass-wiki#4]
Hello,

I used the Plugin with the cloudsystem: "Cloudsystem IO" and it worked perfectly!

Yesterday i switched to CloudNet (Version 3), insalled the plugin and ... it didn't work :(

If i turn Mysql to false, it works! But i have a ClouSystem and i need the MySql connection.

If MySql is turned to true, I can't do /battlepass => An internal error occoured ....

Would be nic, if anyone can help me :)

**Comment by ZakShearman** [comment]
Please send the full error. Although, I don't get what this has to do with ClouSystem and CloudNet?

**Comment by FLO-server** [comment]
Sorry,

my LobbySystem was the Problem. Now it works perfectly!

Thanks for the nice BattlePass Plugin <3
